export const PLAYINGFIELD_WIDTH = 10240;
export const PLAYINGFIELD_HEIGHT = 10240;
export const MASK_WIDTH = 256;
export const MASK_HEIGHT = 256;

export const PLAYINGFIELD_HEIGHT_WITHOUT_MASK =
  PLAYINGFIELD_HEIGHT - MASK_HEIGHT;
export const PLAYINGFIELD_WIDTH_WITHOUT_MASK = PLAYINGFIELD_WIDTH - MASK_WIDTH;
